services:
  devel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: $ROS_DISTRO
    image: oriserobotics/ros-$ROS_DISTRO:devel
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY
      - COLCON_WORKSPACE_FOLDER=$COLCON_WORKSPACE_FOLDER
      - USER=orise
      - SSH_AUTH_SOCK=$SSH_AUTH_SOCK_CONTAINER_PATH
    network_mode: host
    volumes:
      - $SSH_AUTH_SOCK_HOST_PATH:$SSH_AUTH_SOCK_CONTAINER_PATH
      - ~/.gnupg:/home/orise/.gnupg:rw
      - ~/.gitconfig:/etc/gitconfig:ro
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $VOLUMES_FOLDER/$CONTAINER_NAME:/home/orise:rw
      - /etc/localtime:/etc/localtime:ro
    privileged: true
    working_dir: $COLCON_WORKSPACE_FOLDER
    container_name: $CONTAINER_NAME
    stdin_open: true # docker run -i
    tty: true # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        ROS_DISTRO: $ROS_DISTRO
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY
    network_mode: host
    volumes:
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts:rw
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
      - ~/.ssh/id_rsa.pub:/root/.ssh/id_rsa.pub:ro
      - ~/.gitconfig:/etc/gitconfig:ro
      - $SRC_REPOS:/root/src.repos
      # - $APT_CACHE_VOLUME:/var/cache/apt/archives
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /root
    container_name: $CONTAINER_NAME
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: [test_entrypoint.sh, $PACKAGE]
