services:
  devel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: $ROS_DISTRO
        CONTAINER_USER: $CONTAINER_USER
    image: oriserobotics/ros-$ROS_DISTRO:devel
    environment:
      - DISPLAY
      - COLCON_WORKSPACE_FOLDER=$COLCON_WORKSPACE_FOLDER
      - USER=$CONTAINER_USER
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - $VOLUMES_FOLDER/$CONTAINER_NAME:/home/$CONTAINER_USER:rw
      - /etc/localtime:/etc/localtime:ro
    working_dir: $COLCON_WORKSPACE_FOLDER
    container_name: $CONTAINER_NAME
    stdin_open: true # docker run -i
    tty: true # docker run -t

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        ROS_DISTRO: $ROS_DISTRO
    environment:
      - DISPLAY
    volumes:
      - $SRC_REPOS:/root/src.repos
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /root
    container_name: $CONTAINER_NAME
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: [test_entrypoint.sh, $PACKAGE]
