services:
  devel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: $ROS_DISTRO
    image: oriserobotics/ros-$ROS_DISTRO:devel
    environment:
      - COLCON_WORKSPACE_FOLDER=$COLCON_WORKSPACE_FOLDER
      - USER=$CONTAINER_USER
      - USER_UID=$USER_UID
      - USER_GID=$USER_GID
    volumes:
      - home:/home/$CONTAINER_USER:rw
      - /etc/localtime:/etc/localtime:ro
    stdin_open: true # docker run -i
    tty: true # docker run -t
    tmpfs: /tmp:exec

volumes:
  home:
