services:
  devel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: $ROS_DISTRO
    image: oriserobotics/ros-$ROS_DISTRO:devel
    environment:
      - COLCON_WORKSPACE_FOLDER=$COLCON_WORKSPACE_FOLDER
      - USER=$CONTAINER_USER
      - USER_UID=$USER_UID
      - USER_GID=$USER_GID
    volumes:
      - home:/home/$CONTAINER_USER:rw
      - /etc/localtime:/etc/localtime:ro
    stdin_open: true # docker run -i
    tty: true # docker run -t
    tmpfs: /tmp:exec

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        ROS_DISTRO: $ROS_DISTRO
    environment:
      - DISPLAY
    volumes:
      - $SRC_REPOS:/root/src.repos
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /root
    stdin_open: true # docker run -i
    tty: true # docker run -t
    entrypoint: [test_entrypoint.sh, $PACKAGE]
    tmpfs: /tmp

volumes:
  home:
