####### TEST BUILD #######
ARG ROS_DISTRO

FROM ros:${ROS_DISTRO}-ros-core

# install packages
RUN apt-get update && apt-get install -q -y --no-install-recommends \
    dirmngr \
    gnupg2 \
    && rm -rf /var/lib/apt/lists/*

# install bootstrap tools
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    git \
    python3-colcon-mixin \
    python3-rosdep \
    python3-vcstool \
    python3-colcon-common-extensions \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /root
COPY test_entrypoint.sh /usr/bin/

CMD ["bash"]