name: "container-scan"

on:
  push:
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:
jobs:
  docker-best-practices:
    strategy:
      matrix:
        ros-distro: [galactic, foxy]
    env:
      ROS_DISTRO: ${{ matrix.ros-distro }}
      # TRIVY_IGNORE_UNFIXED: 1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: docker build --build-arg ROS_DISTRO="$ROS_DISTRO" -t oriserobotics/ros-"$ROS_DISTRO":devel .

    - uses: Azure/container-scan@v0
      with:
        image-name: oriserobotics/ros-${{ env.ROS_DISTRO }}:devel
