name: "dockerhub-deploy"

on: 
  push:
    branches:
      - master
      - main

jobs:
  dockerhub-deploy:
    strategy:
      matrix:
        ros-distro: [galactic, foxy]
    env:
      ROS_DISTRO: ${{ matrix.ros-distro }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: docker/login-action@v1
      name: Login to DockerHub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - run: docker build --build-arg ROS_DISTRO="$ROS_DISTRO" -t oriserobotics/ros-"$ROS_DISTRO":devel .
    - run: docker push oriserobotics/ros-"$ROS_DISTRO":devel
