name: super-lint
on:
  pull_request:
  workflow_dispatch:
jobs:
  super-lint:
    runs-on: ubuntu-latest
    steps:
    - name: git checkout
      uses: actions/checkout@v2
    - name: super lint
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FILTER_REGEX_EXCLUDE: \.github\/pull_request_template.md
